change actions

diff --git a/.github/workflows/prometheus.yml b/.github/workflows/prometheus.yml
--- a/.github/workflows/prometheus.yml
+++ b/.github/workflows/prometheus.yml
@@ -1,29 +1,22 @@
-name: "fahcsim.grafana_stack.prometheus"
-on:
-  push:
-    paths:
-      - 'roles/prometheus/**'
-      - 'molecule/prometheus/**'
-      - '.github/workflows/prometheus.yml'
+---
+name: CI
+'on':
   pull_request:
-    paths:
-      - 'roles/prometheus/**'
-      - 'molecule/prometheus/**'
-      - '.github/workflows/prometheus.yml'
+  push:
+    branches:
+      - master
+defaults:
+  run:
+    working-directory: ansible_collections/fahcsim/grafana_stack
+
 jobs:
-  molecule:
+
+  lint:
+    name: Lint
     runs-on: ubuntu-latest
-    strategy:
-      fail-fast: true
-      matrix:
-        distro:
-          - ubuntu2204
-          - debian11
-        collection_role:
-          - prometheus
     steps:
-      - name: Check out the code
-        uses: actions/checkout@v1
+      - name: Check out the codebase.
+        uses: actions/checkout@v2
         with:
           path: ansible_collections/fahcsim/grafana_stack
 
@@ -31,12 +24,39 @@ jobs:
         uses: actions/setup-python@v2
         with:
           python-version: '3.x'
+
+      - name: Install test dependencies.
+        run: pip3 install yamllint ansible-core ansible-lint
+
+      - name: Lint code.
+        run: |
+          yamllint .
+          ansible-lint
+  integration:
+    name: Integration
+    runs-on: ${{ matrix.os }}
+    strategy:
+      matrix:
+        os:
+          - ubuntu-latest
+
+    steps:
+      - name: Check out the codebase.
+        uses: actions/checkout@v2
+        with:
+          path: ansible_collections/fahcsim/grafana_stack
       - name: Install test dependencies.
         run: pip3 install ansible molecule[docker] yamllint ansible-lint
-      - name: Run Molecule tests.
-        run: molecule test -s prometheus
+      - name: Set up the test environment.
+        run: |
+          cp tests/ansible.cfg ./ansible.cfg
+          cp tests/inventory ./inventory
+      - name: Test the playbook's syntax.
+        run: ansible-playbook tests/test.yml --syntax-check
+      - name: Idempotence check.
+        run: |
+          idempotence=$(mktemp)
+          ansible-playbook tests/test.yml | tee -a ${idempotence}
+          tail ${idempotence} | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)
         env:
-          PY_COLORS: '1'
           ANSIBLE_FORCE_COLOR: '1'
-          MOLECULE_DISTRO: ${{ matrix.distro }}
-          MOLECULE_DEBUG: '1'
